### ISSUE TITLE
Unable to Open/Read Book

### ISSUE THREAD

**Issue by theritikchoure** [rohitg00/DevOps_Books#1]
I clicked on "AWS CSA Ian Berry" Book & it shows me the below message

" Unable to render code block "

there are some more books, which show the same message

![Screenshot (134)](https://user-images.githubusercontent.com/56495602/170621385-91d75de0-2a63-4814-920e-c96e9b052c37.png)

**Comment by rohitg00** [comment]
Thanks for submitting the issue, I will re-upload the same.
